(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(all-the-icons--cache-limit 4096)
 '(all-the-icons-alltheicon-scale-factor 1.4)
 '(all-the-icons-scale-factor 1.4)
 '(bidi-paragraph-direction 'left-to-right)
 '(byte-compile-docstring-max-column 120)
 '(byte-compile-verbose nil)
 '(cider-auto-jump-to-error nil)
 '(cider-auto-select-error-buffer nil)
 '(cider-jack-in-default 'clojure-cli)
 '(cider-repl-use-content-types t)
 '(cider-show-error-buffer 'except-in-repl)
 '(column-number-mode t)
 '(context-menu-mode t)
 '(custom-safe-themes
   '("da75eceab6bea9298e04ce5b4b07349f8c02da305734f7c0c8c6af7b5eaa9738"
     "aec7b55f2a13307a55517fdf08438863d694550565dee23181d2ebd973ebd6b8"
     "636b135e4b7c86ac41375da39ade929e2bd6439de8901f53f88fde7dd5ac3561"
     "944d52450c57b7cbba08f9b3d08095eb7a5541b0ecfb3a0a9ecd4a18f3c28948" default))
 '(doom-modeline-major-mode-icon t)
 '(eldoc-box-only-multi-line t)
 '(eldoc-documentation-strategy 'eldoc-documentation-compose-eagerly)
 '(eldoc-echo-area-use-multiline-p nil)
 '(global-prettify-symbols-mode t)
 '(image-use-external-converter t)
 '(ls-lisp-use-insert-directory-program t)
 '(lsp-eldoc-render-all t)
 '(lsp-enable-indentation nil)
 '(lsp-file-watch-threshold 10000)
 '(lsp-headerline-breadcrumb-enable t)
 '(lsp-headerline-breadcrumb-enable-diagnostics nil)
 '(lsp-keep-workspace-alive nil)
 '(lsp-rust-analyzer-cargo-watch-command "clippy")
 '(lsp-rust-analyzer-display-chaining-hints t)
 '(lsp-rust-analyzer-display-closure-return-type-hints t)
 '(lsp-rust-analyzer-display-lifetime-elision-hints-enable "skip_trivial")
 '(lsp-rust-analyzer-server-display-inlay-hints t)
 '(lsp-tailwindcss-add-on-mode t)
 '(lsp-treemacs-sync-mode t)
 '(lsp-ui-doc-border "slate gray")
 '(lsp-ui-doc-include-signature t)
 '(lsp-ui-doc-max-height 20)
 '(lsp-ui-doc-max-width 100)
 '(lsp-ui-doc-show-with-mouse t)
 '(lsp-ui-doc-use-webkit t)
 '(mouse-1-click-follows-link 'double)
 '(package-selected-packages '(centaur-tabs))
 '(persp-emacsclient-init-frame-behaviour-override
   '(lambda (frame &optional new-frame-p) (persp-switch "main" frame)
      (unless (doom-real-buffer-p (current-buffer))
        (switch-to-buffer (doom-fallback-buffer)))) nil nil "+workspaces-associate-frame-fn")
 '(recentf-auto-cleanup 'mode)
 '(size-indication-mode t)
 '(tab-bar-auto-width-max '(350 20))
 '(tab-bar-mode nil)
 '(tab-bar-tab-name-truncated-max 30)
 '(tool-bar-mode nil)
 '(tooltip-delay 0.5)
 '(tooltip-reuse-hidden-frame nil)
 '(treemacs-eldoc-display 'detailed)
 '(treemacs-follow-mode t)
 '(treemacs-indent-guide-mode t)
 '(treemacs-indentation 3)
 '(treemacs-show-cursor t)
 '(treemacs-width 28)
 '(treemacs-window-background-color '("#1f1720" . "#45395b"))
 '(use-package-always-demand nil)
 '(warning-minimum-level :emergency)
 '(warning-suppress-types '((comp)))
 '(yas-global-mode nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(button ((t (:inherit link :box (:line-width (2 . 2) :color "dark slate gray" :style released-button) :underline nil))))
 '(company-tooltip-common ((t (:inherit company-tooltip :background "#34323e" :foreground "#4f97d7" :underline nil :weight bold))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :foreground "#4f97d7" :underline nil :weight bold))))
 '(eldoc-box-border ((t (:background "slate gray"))))
 '(error ((t (:foreground "#e67f43" :family "Source Code Pro"))))
 '(fixed-pitch ((t (:family "FiraCode Nerd Font" :height 180))))
 '(font-lock-comment-face ((t (:inherit variable-pitch :foreground "#2aa1ae" :slant italic :height 0.9 :family "iMWritingDuo Nerd Font propo"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face :foreground "#83898d" :height 1.1))))
 '(highlight-parentheses-highlight ((nil (:weight ultra-bold))) t)
 '(line-number ((t (:background "#353535" :foreground "#67a08f" :family "JetBrainsMonoNL Nerd Font"))))
 '(lsp-headerline-breadcrumb-path-face ((t (:inherit font-lock-string-face :height 1.05))))
 '(lsp-headerline-breadcrumb-separator-face ((t (:inherit shadow :height 1.2))))
 '(lsp-headerline-breadcrumb-symbols-face ((t (:inherit font-lock-doc-face :weight bold))))
 '(lsp-ui-doc-highlight-hover ((t (:background "dark slate gray"))))
 '(minibuffer-header-face ((t (:extend t :background "DarkSeaGreen1" :foreground "gray10"))))
 '(org-block ((t (:inherit fixed-pitch))))
 '(org-code ((t (:inherit (shadow fixed-pitch)))))
 '(org-document-info ((t (:foreground "dark orange"))))
 '(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
 '(org-document-title ((t (:inherit default :weight bold :foreground "unspecified-fg" :font "ETBookOT" :height 2.0 :underline nil))))
 '(org-indent ((t (:inherit (org-hide fixed-pitch)))))
 '(org-level-1 ((t (:inherit default :weight bold :foreground "unspecified-fg" :font "ETBookOT" :height 1.75))))
 '(org-level-2 ((t (:inherit default :weight bold :foreground "unspecified-fg" :font "ETBookOT" :height 1.5))))
 '(org-level-3 ((t (:inherit default :weight bold :foreground "unspecified-fg" :font "ETBookOT" :height 1.25))))
 '(org-level-4 ((t (:inherit default :weight bold :foreground "unspecified-fg" :font "ETBookOT" :height 1.1))))
 '(org-level-5 ((t (:inherit default :weight bold :foreground "unspecified-fg" :font "ETBookOT"))))
 '(org-level-6 ((t (:inherit default :weight bold :foreground "unspecified-fg" :font "ETBookOT"))))
 '(org-level-7 ((t (:inherit default :weight bold :foreground "unspecified-fg" :font "ETBookOT"))))
 '(org-level-8 ((t (:inherit default :weight bold :foreground "unspecified-fg" :font "ETBookOT"))))
 '(org-link ((t (:foreground "royal blue" :underline t))))
 '(org-meta-line ((t (:inherit (font-lock-comment-face fixed-pitch)))))
 '(org-property-value ((t (:inherit fixed-pitch))))
 '(org-special-keyword ((t (:inherit (font-lock-comment-face fixed-pitch)))))
 '(org-table ((t (:foreground "#83a598" :family "iMWritingQuat Nerd Font Prop"))))
 '(org-tag ((t (:inherit (shadow fixed-pitch) :weight bold :height 0.8))))
 '(org-verbatim ((t (:inherit (shadow fixed-pitch)))))
 '(powerline-active1 ((t (:background "#5d4d7a" :foreground "SystemScrollbar"))))
 '(spaceline-evil-insert ((t (:background "chartreuse3" :foreground "systembackground" :inherit 'mode-line))))
 '(spaceline-evil-normal ((t (:background "DarkGoldenrod2" :foreground "systembackground" :inherit 'mode-line))))
 '(spaceline-highlight-face ((t (:inherit 'mode-line :foreground "systembackground" :background "DarkGoldenrod2"))))
 '(spaceline-read-only ((t (:background "plum3" :foreground "systembackground" :inherit 'mode-line))))
 '(spaceline-unmodified ((t (:background "DarkGoldenrod2" :foreground "systembackground" :inherit 'mode-line))))
 '(tab-bar ((t (:background "#181818" :foreground "#b9b9b9" :weight regular :height 110 :family "NotoSans NF"))))
 '(tab-bar-tab ((t (:background "cornsilk3" :foreground "gray14" :box (:line-width (3 . 3) :color "cornsilk4" :style flat-button) :weight bold :height 100 :width normal))))
 '(tab-bar-tab-inactive ((t (:background "gray14" :foreground "dark gray" :box (:line-width (3 . 3) :color "gray20" :style released-button) :weight semi-bold :height 100 :width normal))))
 '(tab-line ((t (:background "#2e2f46" :foreground "#2e2f46" :box nil :weight regular :height 110 :family "NotoSans Nerd Font"))))
 '(tab-line-highlight ((t (:weight heavy :box (:line-width (10 . 4) :style released-button) :foreground "gainsboro" :background "#2e2f46" :inherit tab-line))))
 '(tab-line-tab ((t (:weight semi-bold :box (:line-width (10 . 4) :style released-button) :foreground "gainsboro" :background "#2e2f46" :inherit tab-line))))
 '(tab-line-tab-current ((t (:foreground "#bbc2cf" :background "#2e2f46" :inherit tab-line-tab))))
 '(tab-line-tab-inactive ((t (:weight medium :box (:line-width (10 . 4) :style flat-button) :foreground "dark gray" :background "#2e2f46" :inherit tab-line))))
 '(tab-line-tab-special ((t (:weight bold :box (:line-width (10 . 4) :style flat-button) :foreground "dark gray" :background "#2e2f46" :inherit tab-line))))
 '(tooltip ((t (:background "#4b4062" :foreground "#b2b2b2" :underline nil :slant normal :weight normal :height 1.0))))
 '(treemacs-directory-face ((t (:foreground "#bbc2cf"))))
 '(treemacs-file-face ((t (:inherit variable-pitch :foreground "gainsboro" :family "JetBrainsMono Nerd Font"))))
 '(treemacs-git-unmodified-face ((t (:inherit treemacs-file-face :height 1.0))))
 '(treemacs-git-untracked-face ((t (:inherit font-lock-doc-face))))
 '(treemacs-nerd-icons-root-face ((t (:inherit treemacs-root-face :weight bold :height 1.0))))
 '(treemacs-root-face ((t (:family "NotoSans Nerd Font" :height 1.1 :weight bold :box (:line-width (4 . 14) :style flat-button) :foreground "cadet blue" :inherit (variable-pitch font-lock-string-face)))))
 '(treemacs-window-background-face ((t (:background "#242530"))))
 '(ts-fold-replacement-face ((t (:foreground unspecified :box nil :inherit font-lock-comment-face :weight light))))
 '(variable-pitch ((t (:family "NotoSans Nerd Font" :height 140)))))
(put 'customize-group 'disabled nil)
(put 'customize-variable 'disabled nil)
(put 'customize-face 'disabled nil)
