33333333
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(all-the-icons--cache-limit 4096)
 '(all-the-icons-alltheicon-scale-factor 1.4)
 '(all-the-icons-scale-factor 1.4)
 '(bidi-paragraph-direction 'left-to-right)
 '(byte-compile-docstring-max-column 120)
 '(byte-compile-verbose nil)
 '(cider-auto-jump-to-error nil)
 '(cider-auto-select-error-buffer nil)
 '(cider-jack-in-default 'clojure-cli)
 '(cider-repl-use-content-types t)
 '(cider-show-error-buffer 'except-in-repl)
 '(column-number-mode t)
 '(context-menu-mode t)
 '(custom-safe-themes
   '("da75eceab6bea9298e04ce5b4b07349f8c02da305734f7c0c8c6af7b5eaa9738" "aec7b55f2a13307a55517fdf08438863d694550565dee23181d2ebd973ebd6b8" "636b135e4b7c86ac41375da39ade929e2bd6439de8901f53f88fde7dd5ac3561" "944d52450c57b7cbba08f9b3d08095eb7a5541b0ecfb3a0a9ecd4a18f3c28948" default))
 '(doom-modeline-battery nil)
 '(doom-modeline-buffer-modification-icon nil)
 '(doom-modeline-github t)
 '(doom-modeline-hud t)
 '(doom-modeline-time nil)
 '(doom-modeline-time-icon nil)
 '(doom-modeline-unicode-fallback t)
 '(doom-modeline-workspace-name nil)
 '(global-prettify-symbols-mode t)
 '(image-use-external-converter t)
 '(ls-lisp-use-insert-directory-program t)
 '(lsp-eldoc-render-all t)
 '(lsp-enable-indentation nil)
 '(lsp-file-watch-threshold 10000)
 '(lsp-headerline-breadcrumb-enable t)
 '(lsp-headerline-breadcrumb-enable-diagnostics nil)
 '(lsp-keep-workspace-alive nil)
 '(lsp-rust-analyzer-cargo-watch-command "clippy")
 '(lsp-rust-analyzer-display-chaining-hints t)
 '(lsp-rust-analyzer-display-closure-return-type-hints t)
 '(lsp-rust-analyzer-display-lifetime-elision-hints-enable "skip_trivial")
 '(lsp-rust-analyzer-server-display-inlay-hints t)
 '(lsp-tailwindcss-add-on-mode t)
 '(lsp-treemacs-sync-mode t)
 '(mouse-1-click-follows-link t)
 '(package-selected-packages '(spaceline-all-the-icons spaceline))
 '(size-indication-mode t)
 '(tab-bar-auto-width-max '(350 20))
 '(tab-bar-mode nil)
 '(tab-bar-tab-name-truncated-max 30)
 '(tool-bar-mode nil)
 '(tooltip-delay 0.5)
 '(tooltip-reuse-hidden-frame nil)
 '(treemacs-width 28)
 '(treemacs-window-background-color '("#1f1720" . "#45395b"))
 '(use-package-always-demand nil)
 '(warning-minimum-level :emergency)
 '(warning-suppress-types '((comp)))
 '(yas-global-mode nil))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(button ((t (:inherit link :box (:line-width (2 . 2) :color "dark slate gray" :style released-button) :underline nil))))
 '(company-tooltip-common ((t (:inherit company-tooltip :background "#34323e" :foreground "#4f97d7" :underline nil :weight bold))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :foreground "#4f97d7" :underline nil :weight bold))))
 '(error ((t (:foreground "#e67f43" :family "Source Code Pro"))))
 '(font-lock-comment-face ((t (:foreground "#2aa1ae" :slant italic :height 0.8))))
 '(highlight-parentheses-highlight ((nil (:weight ultra-bold))) t)
 '(line-number ((t (:background "#353535" :foreground "#67a08f" :family "JetBrainsMonoNL Nerd Font"))))
 '(minibuffer-header-face ((t (:extend t :background "DarkSeaGreen1" :foreground "gray10"))))
 '(mode-line ((t (:background "#222226" :foreground "#b2b2b2" :box (:line-width (1 . 1) :color "#5d4d7a") :height 105))))
 '(mode-line-active ((t (:inherit mode-line))))
 '(mode-line-highlight ((t (:box (:line-width (2 . 2) :color "grey40" :style released-button)))))
 '(powerline-active1 ((t (:background "#5d4d7a" :foreground "SystemScrollbar"))))
 '(spaceline-evil-insert ((t (:background "chartreuse3" :foreground "systembackground" :inherit 'mode-line))))
 '(spaceline-evil-normal ((t (:background "DarkGoldenrod2" :foreground "systembackground" :inherit 'mode-line))))
 '(spaceline-highlight-face ((t (:inherit 'mode-line :foreground "systembackground" :background "DarkGoldenrod2"))))
 '(spaceline-read-only ((t (:background "plum3" :foreground "systembackground" :inherit 'mode-line))))
 '(spaceline-unmodified ((t (:background "DarkGoldenrod2" :foreground "systembackground" :inherit 'mode-line))))
 '(tab-bar ((t (:background "#181818" :foreground "#b9b9b9" :weight regular :height 110 :family "NotoSans NF"))))
 '(tab-bar-tab ((t (:background "cornsilk3" :foreground "gray14" :box (:line-width (3 . 3) :color "cornsilk4" :style flat-button) :weight bold :height 100 :width normal))))
 '(tab-bar-tab-inactive ((t (:background "gray14" :foreground "dark gray" :box (:line-width (3 . 3) :color "gray20" :style released-button) :weight semi-bold :height 100 :width normal))))
 '(tab-line ((t (:background "slategray4" :foreground "#b2b2b2" :box nil :weight regular :height 110 :family "NotoSans Nerd Font"))))
 '(tab-line-highlight ((t (:inherit tab-line :background "slategray3" :foreground "black" :box (:line-width (10 . 4) :style flat-button) :weight bold))))
 '(tab-line-tab ((t (:inherit tab-line :background "slategray3" :foreground "gray14" :box (:line-width (10 . 4) :color "SlateGray3" :style released-button) :weight semi-bold))))
 '(tab-line-tab-current ((t (:inherit tab-line-tab :background "slategray3" :foreground "gray14" :box (:line-width (10 . 4) :color "slategray3" :style flat-button)))))
 '(tab-line-tab-inactive ((t (:inherit tab-line :background "slategray4" :foreground "gray10" :box (:line-width (10 . 4) :color "slategray4" :style flat-button) :weight semi-bold))))
 '(tab-line-tab-special ((t (:inherit tab-line :background "slategray3" :foreground "gray20" :box (:line-width (10 . 4) :color "slategray3" :style flat-button) :weight bold))))
 '(tooltip ((t (:background "#4b4062" :foreground "#b2b2b2" :underline nil :slant normal :weight normal :height 1.0))))
 '(treemacs-directory-face ((t (:foreground "#bbc2cf"))))
 '(treemacs-file-face ((t (:inherit variable-pitch :foreground "gainsboro" :family "JetBrainsMono Nerd Font"))))
 '(treemacs-git-unmodified-face ((t (:inherit treemacs-file-face))))
 '(treemacs-root-face ((t (:family "NotoSans Nerd Font" :height 1.2 :weight bold :box (:line-width (6 . 10) :color "#1f1720") :inherit (variable-pitch font-lock-string-face)))))
 '(ts-fold-replacement-face ((t (:foreground unspecified :box nil :inherit font-lock-comment-face :weight light)))))
(put 'customize-group 'disabled nil)
